### ISSUE TITLE
Simulator missing

### ISSUE THREAD

**Issue by kamalpy** [CentralLabFacilities/hri-sim#1]
Hi,

Hope you guys had a good time at HRI 2018.
Can you  please share the simulator?
It seems really exciting.

Thanks
Kamal

**Comment by warp1337** [comment]
Thx for the interest. I am extremely busy ATM, I will push the Sim. ASAP

**Comment by kamalpy** [comment]
Thanks Florian, please take your time. I heard your interview and you have a lot going on

**Comment by kamalpy** [comment]
Thanks Florian .

**Comment by kw90** [comment]
Is there any update on this? This could really be helpful for my simulations. Thanks for sharing :)
