### ISSUE TITLE
Availability of the simulator

### ISSUE THREAD

**Issue by kosenhitatchi** [CentralLabFacilities/hri-sim#2]
Good afternoon everyone.

I just read your paper regarding this simulator. What a great initiative to share it. It's wonderfull.
As HRI2018 and the RobotCup are over for this year. When do you think to be able release the code?

All the best

**Comment by PhillipSz** [comment]
Yeah, I also read the paper and would be really interested in the source code!

Thanks a lot!

**Comment by LeroyR** [comment]
@warp1337 is currently finishing up his thesis so he is not available to collect/cleanup the code until ~november

 We will try to find a student/user to prepare the release.

**Comment by kosenhitatchi** [comment]
@LeroyR Thanks for your feedback.
@warp1337 Good luck for the redaction :+1:

**Comment by Xia0ben** [comment]
Hello there,
I am interested in this simulator, too =).
Any new developments to share ?
Thanks a lot !

**Comment by electroendjneer** [comment]
Good evening everyone.

Are there news about the code will be release? I need it for my thesis work :(

**Comment by electroendjneer** [comment]
Good evening, everyone.

Is there any news about when the code will be released? I need it for my thesis work :((

**Comment by QAbot-zh** [comment]
Is there any New news about the release work ??

**Comment by LeroyR** [comment]
I talked with @warp1337:
> It is coming 100%, i just dont know when

As he is not working @CentralLabFacilities anymore AND in the process of relocating, I suggest taking "Coming Soon" in the Duke Nukem Forever sense.

Sorry :disappointed:
